(()=>{const C=window.HOLDEM_CONFIG||{},ok=!!(C.url&&C.key&&window.supabase);ACC=window.ACC||{sb:null,user:null};
if(!ok){window.cloudPush=window.cloudPush||(()=>{});window.cloudPull=window.cloudPull||(()=>{});window.acct=()=>toast('Supabase is not configured — edit supabase-config.js');return}
ACC.sb=window.supabase.createClient(C.url,C.key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const clean=x=>(x||'').replace(/[^\w ]/g,'').trim().slice(0,10)||'Player';
window.cloudPush=async()=>{if(!ACC.user)return;clearTimeout(window._saveTimer);window._saveTimer=setTimeout(async()=>{const {error}=await ACC.sb.from('holdem_saves').upsert({user_id:ACC.user.id,data:{sv,stats},updated_at:new Date().toISOString()});if(error)console.warn(error.message)},500)};
window.cloudPull=async(silent=true)=>{if(!ACC.user)return;const {data,error}=await ACC.sb.from('holdem_saves').select('data,updated_at').eq('user_id',ACC.user.id).maybeSingle();if(error){if(!silent)toast('Cloud save could not be loaded');return}
const remoteDate=Date.parse(data?.updated_at||'')||0;if(data?.data?.sv&&remoteDate>(Number(sv.ts)||0)){Object.assign(sv,data.data.sv);Object.assign(stats,data.data.stats||{});localStorage.setItem('holdem-save',JSON.stringify(sv));localStorage.setItem('holdem-stats',JSON.stringify(stats));theme();if(!silent)toast('Cloud save loaded')}else{cloudPush();if(!silent)toast('Your local save was kept and uploaded')}render()};
window.acct=async kind=>{const em=(document.getElementById('em')?.value||'').trim(),pw=document.getElementById('pw')?.value||'',dn=clean(document.getElementById('dn')?.value||em.split('@')[0]);if(!em||pw.length<6)return toast('Enter an email and a password of 6+ characters');let r;try{r=kind==='up'?await ACC.sb.auth.signUp({email:em,password:pw,options:{data:{display_name:dn},emailRedirectTo:location.origin+location.pathname}}):await ACC.sb.auth.signInWithPassword({email:em,password:pw});if(r.error)return toast(r.error.message);if(kind==='up'&&!r.data.session)return toast('Check your email to confirm your account');ACC.user=r.data.user||ACC.user;sv.name=dn;save();await cloudPull(true);toast(kind==='up'?'Account created':'Logged in');scr('acct')}catch(e){toast('Account service unavailable')}};
window.updateDisplayName=async()=>{if(!ACC.user)return;const dn=clean(document.getElementById('dn')?.value);const {error}=await ACC.sb.auth.updateUser({data:{display_name:dn}});if(error)return toast(error.message);sv.name=dn;save();toast('Display name saved');scr('acct')};
window.resetPassword=async()=>{const em=(document.getElementById('em')?.value||'').trim();if(!em)return toast('Enter your email first');const {error}=await ACC.sb.auth.resetPasswordForEmail(em,{redirectTo:location.origin+location.pathname});toast(error?'Reset email could not be sent':'Password reset email sent')};
window.changePassword=async()=>{const pw=document.getElementById('newpw')?.value||'';if(pw.length<6)return toast('Password must be at least 6 characters');const {error}=await ACC.sb.auth.updateUser({password:pw});toast(error?'Password could not be changed':'Password changed')};
window.logout=async()=>{try{await ACC.sb.auth.signOut()}catch(e){}ACC.user=null;leave();scr('acct')};
const baseScr=window.scr;window.scr=function(n){if(n!=='acct')return baseScr(n);const o=document.getElementById('ov'),c=document.getElementById('ovc');o.hidden=false;if(!ACC.sb){c.innerHTML='<h2>Account</h2><p class="note">Edit supabase-config.js, then refresh.</p><button onclick="scr(\'menu\')">Back</button>';return}
if(ACC.user){const dn=clean(ACC.user.user_metadata?.display_name||sv.name);c.innerHTML='<h2>Account</h2><p class="note">Signed in as '+ACC.user.email+'</p><input class="in" id="dn" maxlength="10" value="'+dn+'"><div class="mm"><button class="p" onclick="updateDisplayName()">Save name</button><button onclick="cloudPull(false)">Load cloud save</button><button onclick="cloudPush();toast(\'Save queued\')">Save now</button></div><input class="in" id="newpw" type="password" minlength="6" placeholder="New password"><div class="mm"><button onclick="changePassword()">Change password</button><button onclick="logout()">Log out</button><button onclick="scr(\'menu\')">Back</button></div>'}
else{c.innerHTML='<h2>Account</h2><p class="note">Your account stores coins, unlocks, stats and your display name.</p><input class="in" id="dn" maxlength="10" placeholder="Display name"><input class="in" id="em" type="email" placeholder="Email"><input class="in" id="pw" type="password" minlength="6" placeholder="Password (6+ characters)"><div class="mm"><button class="p" onclick="acct(\'in\')">Log in</button><button onclick="acct(\'up\')">Create account</button><button onclick="resetPassword()">Forgot password</button><button onclick="scr(\'menu\')">Back</button></div>'}};
ACC.sb.auth.onAuthStateChange((event,session)=>{ACC.user=session?.user||null;if(event==='SIGNED_IN'||event==='PASSWORD_RECOVERY')scr('acct');if(event==='SIGNED_IN')cloudPull(true);render()});
ACC.sb.auth.getSession().then(({data})=>{ACC.user=data.session?.user||null;if(ACC.user)cloudPull(true)}).catch(()=>{});
})();