function showdown(){reveal=true;const alive=P.filter(p=>!p.out&&!p.fold);
 alive.forEach(p=>p.sc=best([...p.h,...board]));
 const lv=[...new Set(P.filter(p=>p.tot>0).map(p=>p.tot))].sort((a,b)=>a-b);let prev=0;const won={};
 lv.forEach(l=>{let amt=0;P.forEach(p=>amt+=Math.max(0,Math.min(p.tot,l)-prev));prev=l;
  let el=alive.filter(p=>p.tot>=l);if(!el.length)el=alive;
  let w=[el[0]];el.slice(1).forEach(p=>{const c=cmp(p.sc,w[0].sc);if(c>0)w=[p];else if(!c)w.push(p)});
  const sh=Math.floor(amt/w.length);w.forEach(p=>{p.chips+=sh;won[p.n]=(won[p.n]||0)+sh});
  w[0].chips+=amt-sh*w.length;won[w[0].n]+=amt-sh*w.length});
 winners=Object.keys(won);say(Object.entries(won).map(([n,a])=>`${n} wins ${a} with ${hname(P.find(p=>p.n==n).sc).toLowerCase()}`).join(' · '));finish()}
function finish(){const pp=pot(),won=winners.includes('You');stats.streak=won?(stats.streak||0)+1:0;stats.bs=Math.max(stats.bs||0,stats.streak);if(stats.streak>=3)unlock('streak3');const wp=P.find(p=>p.n==winners[0]);sv.hist=[...(sv.hist||[]),{w:won,t:`${won?'You':winners.join(' & ')} took ${pp}${wp&&wp.sc?' with '+hname(wp.sc).toLowerCase():''}`}].slice(-10);if(won&&P[0].sc)sv.bestCat=Math.max(sv.bestCat??-1,P[0].sc[0]);stats.hands++;if(winners.includes('You')){stats.won++;stats.big=Math.max(stats.big,pp);const e=10+Math.floor(pp/20);sv.coins+=e;toast(`You won ${pp} · +${e} coins`);unlock('win');if(stats.won>=10)unlock('reg');if(pp>=800)unlock('big');if(P[0].sc&&P[0].sc[0]>=4)unlock('str');if(P[0].sc&&P[0].sc[0]>=6)unlock('boat');if(pp>=300)confetti();if(P[0].chips>=3000)unlock('rich');snd(880,.15);setTimeout(()=>snd(1100,.25),160)}done=true;P.forEach(p=>p.bet=0);save();if(NET.on){const h=hid;setTimeout(()=>{if(done&&h==hid)hand()},7000)}try{localStorage.setItem('holdem-stats',JSON.stringify(stats))}catch(e){}render()}
function strength(p){if(!board.length){const a=p.h[0]%13,b=p.h[1]%13,hi=Math.max(a,b),lo=Math.min(a,b);return Math.min(1,.15+(hi+lo)/24*.35+(a==b?.3+hi/40:0)+((p.h[0]/13|0)==(p.h[1]/13|0)?.05:0)+(hi-lo<=2?.04:0))}const s=best([...p.h,...board]);return [.25+(s[1]||0)/12*.12,.5+(s[1]||0)/12*.1,.68,.78,.85,.88,.93,1,1][s[0]]}
function bot(i){const p=P[i],tc=curBet-p.bet,s=strength(p),r=Math.random(),need=tc/(pot()+tc||1);const raiseTo=()=>Math.min(p.bet+p.chips,Math.max(curBet+minRaise,curBet+Math.round(pot()*(.4+s*.6)/10)*10));if(!tc)return(s>.62&&r<.6*p.a||r<.06*p.a)&&p.chips>0?act(i,'raise',raiseTo()):act(i,'call');if(s<need*1.15-.03+r*.1+p.t&&!(tc<=p.chips*.05&&s>.25)&&r>.05)return act(i,'fold');if(p.chips>tc&&(s>.75&&r<.5*p.a||r<.04*p.a))return act(i,'raise',raiseTo());act(i,'call')}
const QS={Tight:['Patience.','I like my spot.','Hmm.'],'Calling station':['I call.','Just looking.','Why not?'],Maniac:['All gas!','Scared money!','Bet bigger!']};
function quip(p){const q=QS[p.sty];p.q=q[Math.random()*q.length|0];setTimeout(()=>{p.q='';render()},2200)}
const card=(c,hide,nw)=>hide?'<div class="c back"></div>':`<div class="c s${c/13|0} ${nw?'new':''}">${RK[c%13]}<span>${SU[c/13|0]}</span></div>`;
function seat(p,i,show){const hn=p.sc&&!p.fold?`<div class="tag">${hname(p.sc)}</div>`:'';return `<div class="name">${p.n}${i==dealer&&!p.out?' <span class="tag">(dealer)</span>':''}</div>${p.sty?'<div class="tag">'+p.sty+'</div>':''}${p.q?'<div class="q">“'+p.q+'”</div>':''}<div class="chips">${p.out?'out':p.chips}${p.all&&!p.out?' · all in':''}</div><div class="hand">${p.out?'':p.h.map(c=>card(c,!show)).join('')}</div><div class="bet">${p.fold?'folded':p.bet?'bet '+p.bet:''}</div>${hn}`}
function render(){if(!P)return;if(NET.host&&NET.on)bcast();document.getElementById('bots').innerHTML=P.slice(1).map((p,k)=>`<div class="seat ${p.fold?'fold':''} ${p.out?'out':''} ${!done&&cur==k+1?'act':''} ${done&&winners.includes(p.n)?'win':''}">${seat(p,k+1,reveal&&!p.fold)}</div>`).join('');const m=document.getElementById('me');m.className='seat me '+(P[0].fold?'fold ':'')+(!done&&cur==0?'act':'')+(done&&winners.includes('You')?' win':'');m.innerHTML=seat(P[0],0,true);if(!done&&!P[0].fold&&!P[0].out){let t='';if(sv.set.hand&&board.length)t='You have '+hname(best([...P[0].h,...board])).toLowerCase();if(sv.set.eq){const e=equity();t+=(t?' · ':'')+'Win chance '+e+'%'}if(t)m.innerHTML+=`<div class="tag">${t}</div>`+(sv.set.eq?`<div class="eq"><i style="width:${eqV}%"></i></div>`:'')}document.getElementById('pot').textContent='Pot '+pot()+'  ·  Blinds '+SB+'/'+BB;document.getElementById('st').textContent=`Coins ${sv.coins} · Hands ${stats.hands} · Won ${stats.won} · Biggest pot won ${stats.big}`;document.getElementById('board').innerHTML=[0,1,2,3,4].map(k=>board[k]!=null?card(board[k],0,k>=shown):'<div class="c empty"></div>').join('');shown=board.length;document.getElementById('log').innerHTML=logs.map(l=>`<div>${l}</div>`).join('');const bar=document.getElementById('bar'),me=P[0];if(done){if(NET.c){bar.innerHTML='<span class="note">Next hand starts automatically…</span>';return}const over=me.out||P.filter(p=>!p.out).length==1;bar.innerHTML=(me.out&&sv.perks.rebuy?`<button onclick="rebuy()">Use rebuy token (${sv.perks.rebuy})</button>`:'')+`<button class="p" onclick="${over?'newGame()':'hand()'}">${over?'New game':'Deal next hand'}</button>`;return}if(cur!=0||me.fold||me.all){bar.innerHTML=`<span class="note">${me.fold?'You folded. ':''}${me.all&&cur!=0&&!me.fold?'You are all in. ':''}${cur<0?'Running it out…':cur==0?'':'Waiting for '+P[cur].n+'…'}</span>`;return}const tc=curBet-me.bet,max=me.bet+me.chips,min=Math.min(curBet+minRaise,max);if(rv<min||rv>max)rv=min;let h=`<button onclick="act(0,'fold')">Fold</button><button class="p" onclick="act(0,'call')">${tc?'Call '+Math.min(tc,me.chips):'Check'}</button>`;if(me.chips>tc&&min<max)h+=`<input type="range" id="rs" min="${min}" max="${max}" step="10" value="${rv}" oninput="rv=+this.value;document.getElementById('rb').textContent=lab()" aria-label="Raise amount"><button id="rb" onclick="act(0,'raise',rv)">${lab()}</button><button onclick="qb(.5)">½ pot</button><button onclick="qb(1)">Pot</button>`;if(me.chips>tc)h+=`<button onclick="act(0,'raise',${max})">All in</button>`;bar.innerHTML=h}
const lab=()=>(curBet?'Raise to ':'Bet ')+rv;