const BOTS=[['Ada','Tight',.08,.8],['Bruno','Calling station',-.1,.3],['Chen','Maniac',-.05,1.6]];
function seatList(){return [['You','',0,1],...BOTS].slice(0,sv.set.bots+1)}
function attach(){}
function quip(p){const q={Tight:['Patience.','I like my spot.','Hmm.'],'Calling station':['I call.','Just looking.','Why not?'],Maniac:['All gas!','Scared money!','Bet bigger!']}[p.sty];p.q=q[Math.random()*q.length|0];setTimeout(()=>{p.q='';render()},2200)}
function toast(t){const e=document.getElementById('toast');e.textContent=t;e.className='show';clearTimeout(tt);tt=setTimeout(()=>e.className='',2600)}
function unlock(id){if(!sv.ach.includes(id)){sv.ach.push(id);sv.coins+=50;save();toast('Achievement unlocked +50 coins')}}
function theme(){const g=t=>SHOP.find(x=>x.id==sv.eq[t]),st=document.documentElement.style;st.setProperty('--f1',g('felt').v[0]);st.setProperty('--f2',g('felt').v[1]);st.setProperty('--back',g('back').v);const f=g('face').v;st.setProperty('--card',f.card);f.c.forEach((k,i)=>st.setProperty('--c'+i,k))}
function rebuy(){if(!sv.perks.rebuy)return;sv.perks.rebuy--;save();P[0].out=false;P[0].chips=sv.set.chips;hand()}
function play(){document.getElementById('ov').hidden=true;if(!P)newGame()}
function scr(n){const o=document.getElementById('ov'),c=document.getElementById('ovc');o.hidden=false;if(n=='load')c.innerHTML='<div class="logo">Hold\'em</div><div class="ld"><i></i></div>';else if(n=='menu')c.innerHTML='<div class="logo">Hold\'em</div><div class="coin">'+sv.coins+' coins</div><div class="mm"><button class="p" onclick="play()">'+(P?'Resume':'Play')+'</button>'+(P?'<button onclick="newGame();play()">New game</button>':'')+'<button onclick="scr(\'set\')">Settings</button><button onclick="scr(\'stats\')">Stats</button><button onclick="scr(\'ach\')">Achievements</button></div>';else if(n=='set')c.innerHTML='<h2>Settings</h2><div class="mm"><button onclick="sv.set.snd=!sv.set.snd;save();scr(\'set\')">Sound: '+(sv.set.snd?'On':'Off')+'</button><button onclick="sv.set.hand=!sv.set.hand;save();scr(\'set\')">Hand labels: '+(sv.set.hand?'On':'Off')+'</button><button onclick="scr(\'menu\')">Back</button></div>';else if(n=='stats')c.innerHTML='<h2>Stats</h2><div class="ach"><span>Hands played</span><b>'+stats.hands+'</b></div><div class="ach"><span>Hands won</span><b>'+stats.won+'</b></div><div class="ach"><span>Biggest pot won</span><b>'+stats.big+'</b></div><button onclick="scr(\'menu\')">Back</button>';else c.innerHTML='<h2>Achievements</h2><p class="note">Achievements are earned while playing.</p><button onclick="scr(\'menu\')">Back</button>'}
function cloudPush(){}
function setb(){document.getElementById('mt').textContent=sv.set.snd?'Sound on':'Sound off'}
theme();setb();scr('load');setTimeout(()=>scr('menu'),1200);