window.ACC=window.ACC||{sb:null,user:null};const BOTS=[['Ada','Tight',.08,.8],['Bruno','Calling station',-.1,.3],['Chen','Maniac',-.05,1.6]];
const ACH={win:['First blood','Win a hand'],reg:['Regular','Win 10 hands'],big:['Whale','Win a pot of 800 or more'],str:['Strong hand','Win a showdown with a straight or better'],clean:['Table cleared','Knock out every bot'],streak3:['Hot streak','Win 3 hands in a row'],boat:['Full house','Win a showdown with a full house or better'],rich:['High roller','Finish a hand with 3000+ chips']};
const TIPS=['Position matters: acting last is a real edge.','Fold more often than you think.','Pot odds: call only when the price is right.','Calling stations rarely bluff.','Maniacs will pay you off. Let them bet.'];
const SHOP=[{id:'f0',t:'felt',n:'Classic teal',p:0,v:['#1b4a53','#14363d']},{id:'f1',t:'felt',n:'Crimson room',p:150,v:['#6a2330','#451520']},{id:'f2',t:'felt',n:'Midnight',p:150,v:['#26335f','#161d3b']},{id:'f3',t:'felt',n:'Emerald',p:200,v:['#1f6b45','#134a2e']},{id:'f4',t:'felt',n:'Violet',p:250,v:['#4d2f73','#2e1b47']},{id:'b0',t:'back',n:'Oxblood',p:0,v:'repeating-linear-gradient(45deg,#7a2630,#7a2630 4px,#5c1b24 4px,#5c1b24 8px)'},{id:'b1',t:'back',n:'Navy dots',p:100,v:'radial-gradient(#6f8fd8 22%,#1a2a55 24%) 0 0/8px 8px'},{id:'b2',t:'back',n:'Gold stripe',p:200,v:'repeating-linear-gradient(90deg,#c9a45c,#c9a45c 3px,#8a6b2c 3px,#8a6b2c 6px)'},{id:'b3',t:'back',n:'Checker',p:200,v:'repeating-conic-gradient(#222 0 25%,#ddd 0 50%) 0 0/12px 12px'},{id:'k0',t:'face',n:'Classic faces',p:0,v:{card:'#f7f3ea',c:['#1a1a1a','#b3342f','#b3342f','#1a1a1a']}},{id:'k1',t:'face',n:'Four colours',p:250,v:{card:'#f7f3ea',c:['#1a1a1a','#b3342f','#1f5fbf','#1f7a3a']}},{id:'k2',t:'face',n:'Night cards',p:200,v:{card:'#1d2430',c:['#e8e4d8','#ff7b72','#ff7b72','#e8e4d8']}},{id:'rebuy',t:'perk',n:'Rebuy token',p:60,d:'Return with a fresh stack after busting. Stackable.'},{id:'stack',t:'perk',n:'Deep stack',p:400,d:'Start each game with 500 extra chips. One-time.'}];
function toast(t){const e=document.getElementById('toast');e.textContent=t;e.className='show';clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.className='',2600)}
function unlock(id){if(sv.ach.includes(id))return;sv.ach.push(id);sv.coins+=50;save();toast('Achievement: '+ACH[id][0]+' +50 coins')}
function theme(){const g=t=>SHOP.find(x=>x.id==sv.eq[t]),st=document.documentElement.style;st.setProperty('--f1',g('felt').v[0]);st.setProperty('--f2',g('felt').v[1]);st.setProperty('--back',g('back').v);const f=g('face').v;st.setProperty('--card',f.card);f.c.forEach((k,i)=>st.setProperty('--c'+i,k))}
function buy(id){const it=SHOP.find(x=>x.id==id);if(sv.coins<it.p)return toast('Not enough coins');sv.coins-=it.p;if(it.t=='perk'){if(id=='rebuy')sv.perks.rebuy++;else if(!sv.own.includes(id))sv.own.push(id)}else{if(!sv.own.includes(id))sv.own.push(id);sv.eq[it.t]=id;theme()}save();toast('Bought '+it.n);scr('shop')}
function equip(id){const it=SHOP.find(x=>x.id==id);if(!it)return;sv.eq[it.t]=id;theme();save();scr('shop')}
function rebuy(){if(!sv.perks.rebuy)return toast('No rebuy tokens');sv.perks.rebuy--;save();P[0].out=false;P[0].chips=sv.set.chips;hand()}
function play(){document.getElementById('ov').hidden=true;if(!P)newGame()}
function scr(n){const o=document.getElementById('ov'),c=document.getElementById('ovc'),coin='<div class="coin">'+sv.coins+' coins</div>';o.hidden=false;
if(n==='load')c.innerHTML='<div class="logo">Hold\'em</div><div class="ld"><i></i></div><div class="note">'+TIPS[Math.random()*TIPS.length|0]+'</div>';
else if(n==='menu')c.innerHTML='<div class="logo">Hold\'em</div>'+coin+'<div class="mm"><button class="p" onclick="play()">'+(P?'Resume':'Play')+'</button>'+(P&&!NET.on&&!NET.c?'<button onclick="newGame();play()">New game</button>':'')+'<button onclick="scr(\'online\')">Play online</button><button onclick="scr(\'shop\')">Shop</button><button onclick="scr(\'set\')">Settings</button><button onclick="scr(\'acct\')">Account</button><button onclick="scr(\'stats\')">Stats</button><button onclick="scr(\'ach\')">Achievements</button></div><div class="note">Win hands to earn coins and spend them in the shop.</div>';
else if(n==='online')c.innerHTML='<h2>Play online</h2><p class="note">Online tables use Supabase Realtime. Sign in first.</p><input class="in" id="nm" maxlength="10" placeholder="Your name" value="'+(sv.name||'')+'"><div class="mm"><button class="p" onclick="netHost()">Create table</button></div><input class="in" id="jc" maxlength="5" placeholder="Table code"><div class="mm"><button onclick="netJoin()">Join table</button><button onclick="scr(\'menu\')">Back</button></div>';
else if(n==='lobby')c.innerHTML='<h2>Your table</h2><div class="code">'+(NET.code||'')+'</div><p class="note">Share the 5-character code. Players need accounts.</p><div class="mm"><button class="p" onclick="netStart(true)">Start, fill with bots</button><button onclick="netStart(false)">Start humans only</button><button onclick="leave()">Close table</button></div>';
else if(n==='wait')c.innerHTML='<h2>Joined</h2><p class="note">Waiting for the host to start the game…</p><button onclick="leave()">Leave</button>';
else if(n==='shop')c.innerHTML='<h2>Shop</h2>'+coin+'<div class="grid">'+SHOP.map(it=>{const own=sv.own.includes(it.id),on=sv.eq[it.t]==it.id,sw=it.t=='felt'?('background:radial-gradient('+it.v[0]+','+it.v[1]+')'):it.t=='back'?('background:'+it.v):it.t=='face'?('background:'+it.v.card):'',b=it.t=='perk'?(own?'<span class="tag">Owned</span>':'<button onclick="buy(\''+it.id+'\')">'+it.p+' coins</button>'):on?'<span class="tag">Equipped</span>':own?'<button onclick="equip(\''+it.id+'\')">Equip</button>':'<button onclick="buy(\''+it.id+'\')">'+it.p+' coins</button>';return '<div class="item"><div class="sw" style="'+sw+'">'+(it.id=='rebuy'?'x'+sv.perks.rebuy:it.id=='stack'?'+500':it.t=='face'?it.v.c.map((k,i)=>'<span style="color:'+k+'">'+SU[i]+'</span>').join(''):'')+'</div><b>'+it.n+'</b><small>'+ (it.d||(it.t=='felt'?'Table felt':it.t=='face'?'Card faces':'Card back'))+'</small>'+b+'</div>'}).join('')+'</div><button onclick="scr(\'menu\')">Back</button>';
else if(n==='set')c.innerHTML='<h2>Settings</h2><div class="ach"><span>Sound</span><button onclick="tog(\'snd\')">'+(sv.set.snd?'On':'Off')+'</button></div><div class="ach"><span>Hand labels</span><button onclick="tog(\'hand\')">'+(sv.set.hand?'On':'Off')+'</button></div><div class="ach"><span>Win chance</span><button onclick="tog(\'eq\')">'+(sv.set.eq?'On':'Off')+'</button></div><p><button onclick="rs()">Reset saved progress</button></p><button onclick="scr(\'menu\')">Back</button>';
else if(n==='stats'){const r=[['Hands played',stats.hands],['Hands won',stats.won],['Win rate',stats.hands?Math.round(stats.won/stats.hands*100)+'%':'-'],['Biggest pot won',stats.big],['Best streak',stats.bs||0]];c.innerHTML='<h2>Stats</h2>'+r.map(x=>'<div class="ach"><span>'+x[0]+'</span><b>'+x[1]+'</b></div>').join('')+'<button onclick="scr(\'menu\')">Back</button>';
else if(n==='ach')c.innerHTML='<h2>Achievements</h2><p class="note">Each unlocked achievement pays 50 coins.</p>'+Object.entries(ACH).map(([k,v])=>'<div class="ach"><span><b>'+v[0]+'</b><br><small>'+v[1]+'</small></span><span class="tag">'+(sv.ach.includes(k)?'Unlocked':'Locked')+'</span></div>').join('')+'<button onclick="scr(\'menu\')">Back</button>';
else if(n==='acct')c.innerHTML='<h2>Account</h2><p class="note">'+(window.ACC?.user?'Signed in':'Use the account button to access external account storage.')+'</p><button onclick="scr(\'menu\')">Back</button>'}
theme();if(typeof setb==='function')setb();scr('load');setTimeout(()=>scr('menu'),2200);