const SUPA_URL='',SUPA_KEY='';
const SU=['♠','♥','♦','♣'].map(x=>x+'\uFE0E'),RK=['2','3','4','5','6','7','8','9','10','J','Q','K','A'],NAMES=['High card','Pair','Two pair','Three of a kind','Straight','Flush','Full house','Four of a kind','Straight flush'];
let sv={coins:100,own:['f0','b0','k0'],eq:{felt:'f0',back:'b0',face:'k0'},hist:[],bestCat:-1,ach:[],perks:{rebuy:0},day:''},msg='',tt;try{const o=JSON.parse(localStorage.getItem('holdem-save'));if(o)sv={...sv,...o}}catch(e){}
sv.eq={face:'k0',...sv.eq};if(!sv.own.includes('k0'))sv.own.push('k0');sv.set={bots:3,hand:true,eq:false,snd:true,speed:850,blind:5,chips:1000,...sv.set};
const save=()=>{sv.ts=Date.now();try{localStorage.setItem('holdem-save',JSON.stringify(sv))}catch(e){}cloudPush()};
const NET={on:false,host:false,c:null,peers:[],fill:true,name:'',code:'',pr:null,in:0};let TN=0;
let SB=10,BB=20,hands=0,winners=[],shown=0,eqK='',eqV=0,mute=false,AC,stats={hands:0,won:0,big:0};try{Object.assign(stats,JSON.parse(localStorage.getItem('holdem-stats')))}catch(e){}
let P,deck,board,dealer=0,cur,phase,curBet,minRaise,done,reveal,logs=[],hid=0,rv=0;
const pot=()=>P.reduce((a,p)=>a+p.tot,0),canAct=p=>!p.out&&!p.fold&&!p.all;
const say=t=>{logs.push(t);if(logs.length>3)logs.shift();snd(/wins/.test(t)?523:/raise|bets/.test(t)?660:/fold/.test(t)?200:440)};
function snd(f,d=.09){if(!sv.set.snd)return;try{AC=AC||new AudioContext();AC.state=='suspended'&&AC.resume();const o=AC.createOscillator(),g=AC.createGain();o.frequency.value=f;g.gain.value=.05;o.connect(g);g.connect(AC.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,AC.currentTime+d);o.stop(AC.currentTime+d)}catch(e){}}
function equity(){const me=P[0],opp=P.filter((p,i)=>i&&!p.out&&!p.fold).length,k=hid+'-'+phase+'-'+opp;if(k==eqK)return eqV;eqK=k;const used=new Set([...me.h,...board]),rest=[...Array(52).keys()].filter(c=>!used.has(c));let w=0,N=250;for(let n=0;n<N;n++){const d=rest.slice().sort(()=>Math.random()-.5),b=[...board];while(b.length<5)b.push(d.pop());const m=best([...me.h,...b]);let r=1;for(let o=0;o<opp;o++){const c=cmp(m,best([d.pop(),d.pop(),...b]));if(c<0){r=0;break}if(!c)r=Math.min(r,.5)}w+=r}return eqV=Math.round(w/N*100)}
const up=()=>sv.set.blind>0&&hands>1&&(hands-1)%sv.set.blind==0;
function qb(f){const me=P[0],max=me.bet+me.chips,min=Math.min(curBet+minRaise,max);rv=Math.max(min,Math.min(max,curBet+Math.round((pot()+curBet-me.bet)*f/10)*10));render()}
const hname=x=>x[0]==8&&x[1]==12?'Royal flush':NAMES[x[0]];
const cmp=(a,b)=>{for(let i=0;i<Math.max(a.length,b.length);i++){const d=(a[i]||0)-(b[i]||0);if(d)return d}return 0};
function sc5(c){const r=c.map(x=>x%13).sort((a,b)=>b-a),fl=c.every(x=>(x/13|0)==(c[0]/13|0)),cnt={};r.forEach(x=>cnt[x]=(cnt[x]||0)+1);const g=Object.keys(cnt).map(Number).sort((a,b)=>cnt[b]-cnt[a]||b-a);const st=g.length==5&&(r[0]-r[4]==4||(r[0]==12&&r[1]==3&&r[4]==0)),wheel=st&&r[0]==12&&r[1]==3;const cat=st&&fl?8:cnt[g[0]]==4?7:cnt[g[0]]==3&&cnt[g[1]]==2?6:fl?5:st?4:cnt[g[0]]==3?3:cnt[g[0]]==2&&cnt[g[1]]==2?2:cnt[g[0]]==2?1:0;return[cat,...(wheel?[3]:g)]}
function best(c){let b=null;(function go(s,st){if(s.length==5){const x=sc5(s);if(!b||cmp(x,b)>0)b=x;return}for(let i=st;i<c.length;i++)go([...s,c[i]],i+1)})([],0);return b}
function nxt(i,f){for(let k=1;k<=P.length;k++){const j=(i+k)%P.length;if(f(P[j]))return j}return-1}
function post(p,a){a=Math.min(a,p.chips);p.chips-=a;p.bet+=a;p.tot+=a;if(!p.chips)p.all=true}
function newGame(){SB=10;BB=20;hands=0;P=seatList().map(([n,sty,t,a])=>({n,sty,t,a,chips:(n=='You'&&sv.own.includes('stack')&&!NET.on?500:0)+sv.set.chips,h:[],bet:0,tot:0,fold:false,all:false,acted:false,out:false}));attach();dealer=P.length-1;logs=[];hand()}
function hand(){P.forEach(p=>{if(p.chips<=0&&!p.out){p.out=true;if(p.n!='You'){sv.coins+=25;save();toast(`Knocked out ${p.n} +25 coins`)}}});const live=P.filter(p=>!p.out);if((P[0].out&&!NET.on)||live.length==1||(NET.on&&!live.some(p=>p.n=='You'||p.c))){done=true;reveal=false;board=board||[];say(NET.on?'Game over. Winner: '+live[0].n:P[0].out?'You are out of chips.':'You cleaned out the table!');if(!P[0].out){sv.coins+=100;toast('Table cleared +100 coins');unlock('clean')}render();return}hands++;if(up()){SB*=2;BB*=2}winners=[];deck=[...Array(52).keys()].sort(()=>Math.random()-.5);board=[];phase=0;done=false;reveal=false;hid++;P.forEach(p=>{p.bet=p.tot=0;p.fold=p.all=p.acted=false;p.sc=null;p.h=p.out?[]:[deck.pop(),deck.pop()]});dealer=nxt(dealer,p=>!p.out);const sb=live.length==2?dealer:nxt(dealer,p=>!p.out),bb=nxt(sb,p=>!p.out);post(P[sb],SB);post(P[bb],BB);curBet=BB;minRaise=BB;logs=[];if(up())say(`Blinds up to ${SB}/${BB}`);say(`New hand. ${P[sb].n} posts ${SB}, ${P[bb].n} posts ${BB}.`);cur=bb;advance(true)}
function act(i,t,amt){if(NET.c){NET.c.send({k:'act',t,amt});return}const p=P[i];if(done||i!=cur||!canAct(p))return;if(t=='raise')amt=Math.min(Math.max(Math.floor(+amt)||0,Math.min(curBet+minRaise,p.bet+p.chips)),p.bet+p.chips);if(t=='fold'){p.fold=true;say(`${p.n} folds`)}else if(t=='call'){const a=Math.min(curBet-p.bet,p.chips);post(p,a);say(a?`${p.n} calls ${a}`:`${p.n} checks`)}else{const was=curBet;post(p,amt-p.bet);if(p.bet>curBet){minRaise=Math.max(minRaise,p.bet-curBet);curBet=p.bet;P.forEach(q=>{if(q!=p)q.acted=false})}say(`${p.n} ${was?'raises to':'bets'} ${p.bet}${p.all?' (all in)':''}`)}if(i&&p.sty&&Math.random()<(t=='fold'?.1:t=='raise'?.35:.05))quip(p);p.acted=true;advance()}
function advance(first){const alive=P.filter(p=>!p.out&&!p.fold);if(alive.length==1){const w=alive[0];winners=[w.n];w.chips+=pot();say(`${w.n} wins ${pot()}`);return finish()}const pend=p=>canAct(p)&&(!p.acted||p.bet<curBet);if(!P.some(pend))return endRound();cur=nxt(cur,pend);render();if(cur!=0){const h=hid,ci=cur,t0=++TN;if(P[ci].c)setTimeout(()=>{if(h==hid&&!done&&TN==t0)act(ci,P[ci].bet<curBet?'fold':'call')},30000);else setTimeout(()=>{if(h==hid&&!done)bot(cur)},sv.set.speed)}}
function endRound(){P.forEach(p=>{p.bet=0;p.acted=false});curBet=0;minRaise=BB;phase++;if(phase>3)return showdown();const n=phase==1?3:1;for(let k=0;k<n;k++)board.push(deck.pop());if(P.filter(canAct).length<2){cur=-1;render();const h=hid;return setTimeout(()=>{if(h==hid)endRound()},1100)}cur=dealer;advance()}