(()=>{if(!ACC.sb)return;const M={code:'',room:null,host:false,uid:null,name:'',peers:[],fill:true};window.HOLDEM_MP=M;
const clean=x=>(x||'').replace(/[^\\w ]/g,'').trim().slice(0,10)||'Player';
function players(){return [['You','',0,1],...M.peers.map(x=>[x.name,'',0,1]),...(M.fill?BOTS:[]).slice(0,Math.max(0,3-M.peers.length))]}
function topic(){return 'holdem-room:'+M.code}
function snapFor(seat){const n=P.length,V=r=>(r-seat+n)%n,self=P[seat]?.n||M.name,hostName=M.name,logs2=logs.map(t=>String(t).replace(/\bYou\b/g,hostName).replace(new RegExp('\\\\b'+self.replace(/[^\\w ]/g,'\\\\$&')+'\\\\b','g'),'You'));return{P:P.map((_,v)=>{const p=P[(v+seat)%n],show=v===0||(reveal&&!p.fold&&!p.out);return{n:v===0?'You':p.n==='You'?hostName:p.n,sty:p.sty,q:p.q,chips:p.chips,bet:p.bet,tot:p.tot,fold:p.fold,all:p.all,out:p.out,h:show?p.h:p.h.map(()=>0),sc:reveal?p.sc:null}}),board,cur:cur<0?-1:V(cur),dealer:V(dealer),curBet,minRaise,done,reveal,winners:winners.map(w=>w==='You'?hostName:w===self?'You':w),logs:logs2,SB,BB,phase,hid}}
async function send(p){if(M.room)await M.room.send({type:'broadcast',event:'game',payload:p})}
async function sync(){if(!M.host||!P||!M.room)return;for(const p of M.peers){const seat=P.findIndex(x=>x.uid===p.uid);if(seat>0)await send({type:'state',target:p.uid,state:snapFor(seat)})}}
const baseRender=window.render,baseAct=window.act,baseNew=window.newGame;
window.render=function(){baseRender();if(M.host&&M.room)sync().catch(()=>{})};
window.seatList=function(){return M.host?players():[['You','',0,1],...BOTS].slice(0,sv.set.bots+1)};
window.attach=function(){if(M.host&&P)M.peers.forEach((x,i)=>{if(P[i+1]){P[i+1].uid=x.uid;P[i+1].c={online:true}}})};
window.act=function(i,t,a){if(!M.host&&M.room){if(i===0)send({type:'act',uid:M.uid,t,amt:a}).catch(()=>toast('Action failed'));return}baseAct(i,t,a)};
window.applySnap=function(s){P=s.P;board=s.board;cur=s.cur;dealer=s.dealer;curBet=s.curBet;minRaise=s.minRaise;done=s.done;reveal=s.reveal;winners=s.winners;logs=s.logs;SB=s.SB;BB=s.BB;phase=s.phase;hid=s.hid;document.getElementById('ov').hidden=true;render()};
async function setup(){M.room=ACC.sb.channel(topic(),{config:{private:true,presence:{key:M.uid}}});M.room.on('broadcast',{event:'game'},({payload})=>{if(payload?.type==='join'&&M.host){if(M.peers.length>=3)return;let name=clean(payload.name),taken=new Set([M.name,'Ada','Bruno','Chen',...M.peers.map(x=>x.name)]),k=0;while(taken.has(name))name=(name.slice(0,8)+(++k)).slice(0,10);M.peers.push({uid:payload.uid,name});M.room.send({type:'broadcast',event:'private',payload:{target:payload.uid,joined:true,seat:M.peers.length,name}});window.scr('lobby')}if(payload?.type==='act'&&M.host&&P){const i=P.findIndex(x=>x.uid===payload.uid);if(i>0)baseAct(i,payload.t,payload.amt)}}).on('broadcast',{event:'private'},({payload})=>{if(payload?.target!==M.uid)return;if(payload.joined){M.seat=payload.seat;M.name=payload.name;window.scr('wait')}if(payload.state)applySnap(payload.state)}).on('presence',{event:'leave'},({key})=>{if(!M.host||!P)return;const peer=M.peers.find(x=>x.uid===key);if(!peer)return;M.peers=M.peers.filter(x=>x.uid!==key);const i=P.findIndex(x=>x.uid===key);if(i>0){P[i].c=null;say(peer.name+' left — bot takes over');if(!done&&P[cur]===P[i])setTimeout(()=>bot(i),500)}render()});return new Promise((resolve,reject)=>M.room.subscribe(async status=>{if(status==='SUBSCRIBED'){try{await M.room.track({uid:M.uid,name:M.name})}catch(e){}resolve()}else if(status==='CHANNEL_ERROR'||status==='TIMED_OUT')reject()})}
window.netHost=async()=>{if(!ACC.user)return toast('Sign in before creating a table');M.uid=ACC.user.id;M.name=clean(document.getElementById('nm')?.value||sv.name||ACC.user.user_metadata?.display_name);sv.name=M.name;M.code=Math.random().toString(36).slice(2,7).toUpperCase();M.host=true;M.peers=[];NET.name=M.name;NET.code=M.code;NET.host=true;try{await setup();window.scr('lobby')}catch(e){leave();toast('Could not connect to online play')}};
window.netJoin=async()=>{if(!ACC.user)return toast('Sign in before joining a table');const code=(document.getElementById('jc')?.value||'').replace(/[^a-z0-9]/gi,'').toUpperCase();if(code.length!==5)return toast('Enter the 5-character code');M.uid=ACC.user.id;M.name=clean(document.getElementById('nm')?.value||sv.name||ACC.user.user_metadata?.display_name);M.code=code;M.host=false;NET.name=M.name;NET.code=code;NET.host=false;NET.c={online:true};try{await setup();await send({type:'join',uid:M.uid,name:M.name});window.scr('wait')}catch(e){leave();toast('Table not found or online service unavailable')}};
window.netStart=async fill=>{if(!M.host||!M.room)return;if(!fill&&!M.peers.length)return toast('Need at least one other player');M.fill=fill;NET.on=true;NET.host=true;baseNew();document.getElementById('ov').hidden=true;render();await send({type:'start'})};
window.leave=async()=>{try{await M.room?.untrack();if(M.room)await ACC.sb.removeChannel(M.room)}catch(e){}M.room=null;M.code='';M.peers=[];M.host=false;NET.on=false;NET.host=false;NET.c=null;NET.peers=[];P=null;hid++;window.scr('menu')};
const baseScr=window.scr;window.scr=function(n){if(n==='lobby'){const c=document.getElementById('ovc');c.innerHTML='<h2>Your table</h2><div class="code">'+M.code+'</div><p class="note">Share this code with friends.</p>'+[M.name,...M.peers.map(x=>x.name)].map((x,i)=>'<div class="ach"><span>'+x+'</span><span class="tag">'+(i?'Joined':'Host')+'</span></div>').join('')+'<div class="mm"><button class="p" onclick="netStart(true)">Start, fill with bots</button><button onclick="netStart(false)">Start humans only</button><button onclick="leave()">Close table</button></div>';document.getElementById('ov').hidden=false;return}if(n==='wait'){const c=document.getElementById('ovc');c.innerHTML='<h2>Joined</h2><p class="note">Waiting for the host to start…</p><button onclick="leave()">Leave</button>';document.getElementById('ov').hidden=false;return}if(n==='online'&&!ACC.user){return baseScr('acct')}return baseScr(n)};
})();